### PR TITLE
fix: marshmallow and marshmallow-annotations causing issues

### PR DESCRIPTION
**Pull request by allisonsuarez**
Signed-off-by: Allison Suarez Miranda <asuarezmiranda@lyft.com>

### Summary of Changes

Get dependency conflict when bumping amundsen-common to latest version on amundsenmetadatalibrary.

### CheckList

Make sure you have checked **all** steps below to ensure a timely review.

- [ ] PR title addresses the issue accurately and concisely. Example: "Updates the version of Flask to v1.0.2"
  - In case you are adding a dependency, check if the license complies with the [ASF 3rd Party License Policy](https://www.apache.org/legal/resolved.html#category-x).
- [ ] PR includes a summary of changes.

### CODE REVIEW

**Review by feng-tao — COMMENTED** [review]
do you need to bump common deps?

**Comment by allisonsuarez** [comment]
> do you need to bump common deps?

Yes, trying to get the Lineage schema on metadata for the new lineage API

**Comment by feng-tao** [comment]
yeah, but you need to update the version number in setup.py?

**Comment by allisonsuarez** [comment]
> yeah, but you need to update the version number in setup.py?

no I can just run the action to do it :)

**Review by feng-tao — APPROVED** [review]

**Pull request merged**
